name: Docker Image CI

on: [workflow_dispatch]


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  
      
    - name: Build the Docker image
      run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} -t ${{ github.repository }}:latest -f ./ActionsAPI/Dockerfile .
          docker push ghcr.io/${{ github.repository }} --all-tags
