name: Deploy to AKS via helm

on:

  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  AKS_Deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Helm tool installer
        uses: Azure/setup-helm@v3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install
        
      - name: Run a multi-line script
        run: |
          helm pull https://ghcr.io/lambergluke/charts/api-aks-testing:1.0.2 --untar --debug
          pwd
          ls -al

